# fly.toml app configuration file generated for delicate-grass-8553 on 2023-06-28T09:23:57+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "delicate-grass-8553"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
